name: Python package

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
      - 'docs/blog/pdf2htmlex/**'
      - '.github/workflows/pdf.yml' 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: show path
      run: echo %PATH%
      shell: cmd
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
        architecture: x64
    - name: run 
      run: |
        cd docs/blog/pdf2htmlex
        dir
        python run.py
        dir
      shell: cmd
    - name: commit file
      run: |
        cd docs/blog/2021/0122
        dir
        git add '0122 马太福音11章.pdf'
        git add *
        git config --global user.name 'GitHub action bot'
        git config --global user.email 'bot@users.noreply.github.com'
        git commit -am "Auto convert PDF2HTML by GitHub Action"
        git push
