name: Python package

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ main ]
    paths:
      - 'docs/blog**'
      - '.github/workflows/pdf.yml' 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v2
    - name: show path
      run: echo %PATH%
      shell: cmd
    - name: run 
      run: |
        cd pdftest
        ls
        start pdf2htmlEX.exe --embed cfijo --dest-dir svg  --optimize-text 1 --bg-format svg t.pdf
        git add *
        git config --global user.name 'Your Name'
        git config --global user.email 'your-username@users.noreply.github.com'
        git commit -am "Automated generated index.html by GitHub Action"
        git push
      shell: cmd

